### ISSUE TITLE
Code Snippet Width Issue In Split Mode Preview

### ISSUE THREAD

**Issue by infosisio** [sn-extensions/simple-markdown-editor#12]
If a line inside of a code block is really really long and you have the split mode on, then on the preview panel you see the border for that code block to have a width limited to the panels width instead of following that really long line; thus when you scroll, you see the remaining line out of the borders of the block.

**Comment by mobitar** [comment]
Screenshot?

**Comment by infosisio** [comment]
@mobitar 
![screenshot_20181227_193830](https://user-images.githubusercontent.com/40072254/50489208-04090d00-0a0f-11e9-91df-279258d9c71c.png)

**Comment by mobitar** [comment]
Fixed in 1.2.6; update via Extensions menu and clear cache if necessary.
