### ISSUE TITLE
Preview mode seems to scale up small images

### ISSUE THREAD

**Issue by mobitar** [sn-extensions/simple-markdown-editor#13]
(Source image is 64x64)

![slack-imgs](https://user-images.githubusercontent.com/3277844/52584311-56539100-2df7-11e9-9224-67dfaa4aa40c.png)

**Comment by DavBE** [comment]
I believe it must be caused by the stylesheet : 
[https://github.com/sn-extensions/simple-markdown-editor/blob/master/app/stylesheets/main.scss#L98](https://github.com/sn-extensions/simple-markdown-editor/blob/master/app/stylesheets/main.scss#L98)

**Comment by mobitar** [comment]
Ah yeah, that must be it. I was trying to say max-width really, because large images were overflowing.
