### ISSUE TITLE
[IOS] Uncommon scrolling behavior in "preview" view.

### ISSUE THREAD

**Issue by MustachedMario** [sn-extensions/simple-markdown-editor#14]
Using the "preview" view on IOS, the scrolling behaves uncommon "sticky".
The edit view instead, scrolls like a charm.

As far as i know, the simple markdown editor is not a third party developed extension, so can you please look at this issue?

**Comment by mobitar** [comment]
Fixed and deployed. Thanks for the heads up.

**Comment by MustachedMario** [comment]
Thanks for fixing this. (not testet currently)

> (on iOS cache might come into play if you don't see the fix immediately. You can try clearing your webview cache from your general system settings).

BTW: Are all mobile extension cached by this way? So switching between notes with different editors doesn't reload the complete extension from the web? If this so, this would save expensive mobile traffic.

**Comment by mobitar** [comment]
All editors are cached, and yes, in most cases in the same app session network requests are not repeated.

As for how to clear the cache to get this editor update, I haven't found a good way for iOS besides uninstalling the app and re-installing. The cache is only cleared when the app itself is updated to a new version. On Android the cache can be cleared from the device Storage settings.

**Comment by MustachedMario** [comment]
Yep, reinstalling does it. Can confirm the fix.
Thanks.
