### ISSUE TITLE
Automatic Code Highlight

### ISSUE THREAD

**Issue by infosisio** [sn-extensions/simple-markdown-editor#5]
If I am not mistaken, highlight.js that is in use by the project for  code highlighting, provides automatic code highlighting (no need to specify language initials after ```).

I think it would be nice to enable this in simple markdown editor (and for the rest of markdown editors too)

**Comment by mobitar** [comment]
Good point. Although, we're using [markdown-it-highlight](https://github.com/tylingsoft/markdown-it-highlight), which is a wrapper on top of highlight.js. Will likely have to fork it to get this functionality.

**Comment by mobitar** [comment]
This is now available in the editor.
