### ISSUE TITLE
Checklists rendered incorrectly in Simple Markdown Editor

### ISSUE THREAD

**Issue by chegeiser** [sn-extensions/simple-markdown-editor#6]
I've noticed that checklists created with the Simple Markdown Editor are preceded with a bullet point - this action is different than with the Simple Task Editor and the Github Flavored Markdown that I believe was used to guide this implementation. The screenshots attached are from the same list, viewed in both the Simple Task Editor and the Simple Markdown Editor. 

![simple markdown editor](https://user-images.githubusercontent.com/17602493/46091447-bbb82580-c167-11e8-9baf-5fd8d36a0228.jpg)
![simple task editor](https://user-images.githubusercontent.com/17602493/46091448-bbb82580-c167-11e8-9be2-b63833f9fa10.jpg)

**Comment by bryvin** [comment]
Probably been realized by now, but this was fixed in commit [445c82d](https://github.com/sn-extensions/simple-markdown-editor/commit/445c82d2af4994ebc9582e05945597dbe36d6b30)
